### ISSUE TITLE
Likely better to have a dictionary which looks up functions

### ISSUE THREAD

**Issue by SimonBiggs** [matthewdeancooper/lightning_prototype#2]
As opposed to using eval on potentially one day remote user inputs:

https://github.com/matthewdeancooper/lightning_proto/blob/649b6bb8ac61daf607a0ef2c8024ac220db6f1b5/lightning_proto/model2D.py#L60

(Say if one day an online streamlit app was being used to provide these CLI parameters)

**Comment by matthewdeancooper** [comment]
Ah yes you're right. This is likely bad practice as it allows the user to evaluate any string of text they want!

**Comment by SimonBiggs** [comment]
> Ah yes you're right. This is likely bad practice as it allows the user to evaluate any string of text they want!

There certainly are valid reasons to use it, for example, it is used within Python's source code for the `namedtuple` definition:

https://github.com/python/cpython/blob/f2df7958fb82cd927e17152b3a1bd2823a76dd3e/Lib/collections/__init__.py#L425-L431

...just... its use needs to be justified.
